### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by otherguy** [waltmoorhouse/FilamentBox#1]
I saw your Octoprint plugin and followed you here. Will you expand on this with photos/screenshots and build instructions?

**Comment by sambald** [comment]
Very much agreed! I have a Prusa with an MMU2 and enclosure and this seems like the perfect thing to mount on top. Having the code and BOM is awesome, but some pictures/build instructions would go a long way!

**Comment by waltmoorhouse** [comment]
Yes, I will update once I get the parts from China and build it. I am hoping the show up in the next week or so.

**Comment by xDazld** [comment]
Any updates on the parts/build?

**Comment by waltmoorhouse** [comment]
Parts came yesterday. Also I was contacted by RepKord and will be basing this build on the RepBox2 instead of a plastic cambro. I have to go out of town so will not be able to work on this until next week, but as soon as I have the build completed, updated BOM and instructions will be posted.
